lib/fetch/http.c: remove unused variable
thanks clang!

fetch/http.c:605:9: error: variable 'r' set but not used [-Werror,-Wunused-but-set-variable]
        int t, r;
               ^